### ISSUE TITLE
 Connection reset by peer

### ISSUE THREAD

**Issue by 2003jiahang** [ybgdgh/L3MVN#14]
Hi authors,

Thanks for the great work!

When I evaluate the pre-trained model, I get an error:
`[22:55:21:744507]:[Metadata] MetadataMediator.cpp(66)::setSimulatorConfiguration : Set new simulator config for scene/stage : data/scene_datasets/hm3d/val/00877-4ok3usBNeis/4ok3usBNeis.basis.glb and dataset : ./data/scene_datasets/hm3d/hm3d_annotated_basis.scene_dataset_config.json which is currently active dataset.
Traceback (most recent call last):
  File "/liu_jia_hang/L3MVN/main_llm_vis.py", line 1010, in <module>
    main()
  File "/liu_jia_hang/L3MVN/main_llm_vis.py", line 150, in main
    envs = make_vec_envs(args)
  File "/liu_jia_hang/L3MVN/envs/__init__.py", line 10, in make_vec_envs
    envs = construct_envs21(args)
  File "/liu_jia_hang/L3MVN/envs/habitat/__init__.py", line 251, in construct_envs21
    envs = VectorEnv(
  File "/liu_jia_hang/L3MVN/envs/habitat/utils/vector_env.py", line 141, in __init__
    self.observation_spaces = [
  File "/liu_jia_hang/L3MVN/envs/habitat/utils/vector_env.py", line 142, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/liu_jia_hang/miniconda3/envs/habitat/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/liu_jia_hang/miniconda3/envs/habitat/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/liu_jia_hang/miniconda3/envs/habitat/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x7f0f25ab4550>
Traceback (most recent call last):
  File "/liu_jia_hang/L3MVN/envs/habitat/utils/vector_env.py", line 549, in __del__
    self.close()
  File "/liu_jia_hang/L3MVN/envs/habitat/utils/vector_env.py", line 416, in close
    write_fn((CLOSE_COMMAND, None))
  File "/liu_jia_hang/miniconda3/envs/habitat/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/liu_jia_hang/miniconda3/envs/habitat/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/liu_jia_hang/miniconda3/envs/habitat/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Segmentation fault (core dumped)`

**Comment by 2003jiahang** [comment]
Can you give me some guidance?

I'd love to reproduce your work!

Thanks.

**Comment by 2003jiahang** [comment]
I resolve this problem，thanks.

**Comment by itak04** [comment]
> I resolve this problem，thanks.

how to solve it
